### ISSUE TITLE
Series 0.9.x

### ISSUE THREAD

**Issue by sideeffffect** [eikek/emil#313]
Hello, could you please create a branch `series/0.9.x` on the commit https://github.com/sideeffffect/emil/commit/d1c896061de1c35ccf4856f88d5776d0cfc0d593 (last before Cats Effect 3) like I have here https://github.com/sideeffffect/emil/tree/series/0.9.x ?

I will then backport https://github.com/eikek/emil/pull/310 to 0.9.x so that we can have this feature while still being on Cats Effect 2.

**Comment by eikek** [comment]
If you want, I can add you as a collaborator to this project? (I create the branch in a minute)

**Comment by eikek** [comment]
Done

**Comment by sideeffffect** [comment]
Yeah, why not :+1: Thanks!
